Fix issue with fstring containing backslash
I was getting this error:
```
File "/home/beeai/agents/rebase_agent.py", line 309
    ),
    ^
SyntaxError: f-string expression part cannot include a backslash
```
I assume it was because of using older version of Python with the centos stream 9 base image.