fix test_set_jira_fields
```
FAILED mcp_server/tests/unit/test_jira_tools.py::test_set_jira_fields[args0-fields0] - assert False
 +  where False = <built-in method startswith of str object at 0x7f3f9731de70>('Successfully')
 +    where <built-in method startswith of str object at 0x7f3f9731de70> = 'Failed to get current issue details: HTTPConnectionPool(host=\'jira\', port=80): Max retries exceeded with url: /rest/api/2/issue/RHEL-12345 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3f97235160>: Failed to resolve \'jira\' ([Errno -2] Name or service not known)"))'.startswith
FAILED mcp_server/tests/unit/test_jira_tools.py::test_set_jira_fields[args1-fields1] - assert False
 +  where False = <built-in method startswith of str object at 0x7f3f9731dfd0>('Successfully')
 +    where <built-in method startswith of str object at 0x7f3f9731dfd0> = 'Failed to get current issue details: HTTPConnectionPool(host=\'jira\', port=80): Max retries exceeded with url: /rest/api/2/issue/RHEL-12345 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3f973b1950>: Failed to resolve \'jira\' ([Errno -2] Name or service not known)"))'.startswith
```

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>
Assisted-by: Cursor(Claude)